media: public/brand

content:
  - name: news
    label: News
    path: content/news
    type: collection
    extension: adoc
    format: code
    create: true
    fields:
      - name: body
        label: AsciiDoc body
        type: rich-text
  - name: blog
    label: Blog
    path: content/blog
    type: collection
    extension: adoc
    format: code
    create: true
    fields:
      - name: body
        label: AsciiDoc body
        type: rich-text